spring.application.name=ChatLobby

spring.datasource.url=jdbc:postgresql://localhost:5432/chatlobbydb
spring.datasource.username=chatuser
spring.datasource.password=chatpass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
